#!/usr/bin/env bash
#shellcheck disable=SC2034,SC2059,SC2145,SC2155

#  void-gitclone
#  Created: 2023/01/27
#  Altered: 2023/01/27
#
#  Copyright (c) 2022-2023, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
set -x

#system
readonly APP="${0##*/}"
readonly _VERSION_='0.0.16-20230127'
readonly DEPENDENCIES=(git)
trap 'printf "\n${red}Interrupted! exiting...\n"; cleanup; exit 0' INT TERM HUP

sh_ambiente() {
	readonly true=0
	readonly false=1
	readonly BOOTLOG="/tmp/$APP-$(sh_diahora).log"
}

info_msg() {
	printf "\033[1m$@\n\033[m"
	return "$true"
}

cleanup() {
	info_msg "Removing temporary files"
	rm -f "$BOOTLOG"
	exit "$false"
}

sh_diahora() {
	DIAHORA=$(date +"%d%m%Y-%T")
	DIAHORA="${DIAHORA//:/}"
	printf "%s\n" "$DIAHORA"
	return "$true"
}

sh_checkroot() {
	if [ "$(id -u)" != "0" ]; then
		die "${red}error: you cannot perform this operation unless you are root.${reset}"
	fi
	return "$true"
}

sh_checkDependencies() {
	local d
	local errorFound=0
	declare -a missing

	for d in "${DEPENDENCIES[@]}"; do
		[[ -z $(command -v "$d") ]] && missing+=("$d") && errorFound=1 && printf "${red}ERROR: I couldn't find the command ${cyan}'$d'${reset}\n"
	done
	if (( errorFound )); then
		echo -e "${yellow}-------------IMPOSSIBLE TO CONTINUE-----------------${reset}"
		echo -e "This script needs the commands listed above" >&2
		echo -e "Install them and/or make sure they are on your \$PATH" >&2
		echo -e "${yellow}----------------------------------------------------${reset}"
		die "${APP} aborted..."
	fi
	return "$true"
}

sh_setvarcolors() {
	# does the terminal support true-color?
	if [[ -n $(command -v "tput") ]]; then
		#tput setaf 127 | cat -v  #capturar saida
		tput sgr0 # reset colors
		bold=$(tput bold)
		reset=$(tput sgr0)
		red=$(tput setaf 1)
		green=$(tput setaf 2)
		yellow=$(tput bold)$(tput setaf 3)
		blue=$(tput setaf 4)
		pink=$(tput setaf 5)
		cyan=$(tput setaf 6)
	else
		red="\e[31m"
		reset="\e[0m"
		bold="\e[1m"
		italic="\e[3m"
		underline="\e[4m"
		green="\e[32m"
		yellow="\e[33m"
		blue="\e[34m"
		pink="\e[35m"
		cyan="\e[36m"
		gray="\e[90m"
		white="\e[97m"
	fi
	return 0
}

DOT() {
	printf "${blue}:: ${reset}"
	return "$true"
}

die() {
	local msg=$1; shift
	printf "$(DOT)${bold}${red}$msg${reset}\n" >&2
	exit "$false"
}

sh_version() {
	printf "${bold}${cyan}${0##*/} v${_VERSION_}${reset}"
	return "$true"
}

sh_gitclone(){
	while read -r -p "Insert a git repository, enter to exit: "
	do
		[ "${REPLY^}" == "" ] && return $false
		echo "${REPLY}" >> "$BOOTLOG"
		git clone "${REPLY}"
		echo
	done
	return "$true"
}

sh_setvarcolors
sh_ambiente
sh_checkDependencies
[[ "$1" = @(-V|-v|version|-version|--version) ]] && { sh_version; exit $(( $# ? 0 : 1 ));}
sh_gitclone "$@"
