#!/usr/bin/env bash
# -*- coding: utf-8 -*-
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
#
#  void-utils-selector - Seletor de utilitários para o Void
#  Created: 2025/02/03 - 00:54
#  Altered: 2025/02/03 - 00:54
#  Updated: sáb 08 fev 2025 20:04:45 -04
#
#  Copyright (c) 2025-2025, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#export LANGUAGE=pt_BR
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=void-utils-selector

# Definir a variável de controle para restaurar a formatação original
reset=$(tput sgr0)

# Definir os estilos de texto como variáveis
bold=$(tput bold)
underline=$(tput smul)   # Início do sublinhado
nounderline=$(tput rmul) # Fim do sublinhado
reverse=$(tput rev)      # Inverte as cores de fundo e texto

# Definir as cores ANSI como variáveis
black=$(tput bold)$(tput setaf 0)
red=$(tput bold)$(tput setaf 196)
green=$(tput bold)$(tput setaf 2)
yellow=$(tput bold)$(tput setaf 3)
blue=$(tput setaf 4)
pink=$(tput setaf 5)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
gray=$(tput setaf 8)
orange=$(tput setaf 202)
purple=$(tput setaf 125)
violet=$(tput setaf 61)
light_red=$(tput setaf 9)
light_green=$(tput setaf 10)
light_yellow=$(tput setaf 11)
light_blue=$(tput setaf 12)
light_magenta=$(tput setaf 13)
light_cyan=$(tput setaf 14)
bright_white=$(tput setaf 15)

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
#set -x
#set -e
shopt -s extglob

#system
declare APP="${0##*/}"
declare _VERSION_="1.2.08-20250208"
declare distro="$(uname -n)"
declare DEPENDENCIES=(tput dialog)
declare ccabec="$APP - Seletor de utilitários para o Void"
declare ctitle="Menu Principal"
declare -A Autils=()
declare -a theme_list=()

MostraErro() { echo "erro: ${red}$1${reset} => comando: ${cyan}'$2'${reset} => result=${yellow}$3${reset}"; }
#trap 'MostraErro "$APP[$FUNCNAME][$LINENO]" "$BASH_COMMAND" "$?"; exit 1' ERR

# Exibir o menu com números e nomes de temas
Autils+=(['void-chroot']='Utilitário para executar chroot')
Autils+=(['void-clonedisk']='Utilitário para clonar discos')
Autils+=(['void-dialog-theme-selector']='Utilitário para selecionar temas para o dialog')
Autils+=(['void-mirror']='Utilitário para configurar repositórios do Void')
Autils+=(['void-maketar']='Utilitário para criar backups com tar')
Autils+=(['void-parted']='Utilitário para particionar disco')
Autils+=(['void-remove-vg']='Utilitário para listar e remover VG (Grupo de Volumes)')
Autils+=(['void-services']='Utilitário para gerenciar serviços do Void')
Autils+=(['void-setfont']='Utilitário para configurar fonte no tty')
Autils+=(['void-testmirror']='Utilitário para testar latência dos mirrors do Void')
Autils+=(['void-wifi']='Utilitário para configurar rede wifi (wpa_supplicant)')
Autils+=(['void-wifi-config']='Utilitário para configurar rede wifi (NetworkManager)')
Autils+=(['void-xrandr']='Utilitário para configurar resolucao de video')
Autils+=(['void-gitclone']='Utilitário para clonar repositórios')
Autils+=(['void-efivar']='Utilitário para listar variáveis UEFI')
Autils+=(['void-runimage']='Utilitário para rodar dispositivos de bloco - like VirtManager')

for key in "${!Autils[@]}"; do
	desc="${Autils[$key]}"
	theme_list+=("$key" "$desc")
done

util_choice=$(dialog \
	--colors \
	--title "$ctitle" \
	--backtitle "$ccabec" \
	--menu "Escolha o utilitário desejado" \
	20 0 2 \
	"${theme_list[@]}" 2>&1 >/dev/tty)

if [ -n "$util_choice" ]; then
	sudo bash "$util_choice"
else
	dialog --msgbox "Nenhum utilitário foi escolhido!" 0 0
fi
