#!/usr/bin/env bash
#shellcheck disable=SC2145,SC2001,SC2188,SC2015,SC2155,SC2317,SC2320,SC2291,SC2034

#  void-wifi
#  Created: 2023/01/16
#  Altered: 2023/01/23
#
#  Copyright (c) 2023-2023, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#debug
export PS4=$'${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
#set -x

#system
readonly APP="${0##*/}"
readonly _VERSION_='0.25.20230123'
readonly	distro=$(uname -n)
readonly DEPENDENCIES=(cat dialog sed printf)
declare _REDE_WIFI="REDE_WIFI"
declare _SENHA_WIFI="SENHA_WIFI"
readonly BOOTLOG="/tmp/void-wifi-$(date +"%d%m%Y-%T" | sed 's/://g').log"
: "${ccabec="$APP v${_VERSION_}"}"
: "${DIALOG=${DIALOG:-"dialog"}}"
reset=$(tput sgr0)
bold=$(tput bold)
red=$(tput setaf 1)
blue=$(tput setaf 4)
yellow=$(tput bold)$(tput setaf 3)
cyan=$(tput setaf 6)

# flag dialog exit status codes
: "${D_OK=0}"
: "${D_CANCEL=1}"
: "${D_HELP=2}"
: "${D_EXTRA=3}"
: "${D_ITEM_HELP=4}"
: "${D_ESC=255}"

# dialog colors
RED="\Z1"
BOLD="\Zb"
RESET="\Zn"
LABEL="${BOLD}Use as teclas ${RED}PARA CIMA ${RESET}e ${BOLD}${RED}PARA BAIXO ${RESET}para navegar.\n\
Use ${BOLD}${RED}TAB ${RESET}para alternar entre os botões e ${BOLD}${RED}ENTER ${RESET}para selecionar."
trap 'printf "\n${red}Interrupted! exiting...\n"; cleanup; exit 0' INT TERM HUP

info_msg() {
	printf "\033[1m$@\n\033[m"
}

cleanup() {
	info_msg "Removing temporary files..."
	rm -fv "$BOOTLOG"
	info_msg "exit 1"
	exit 1
}

sh_update_wpa_suplicant() {
	msg "INFO" "Ajustando wpa_supplicant.conf"
   [[ ! -e /etc/wpa_supplicant/wpa_supplicant.conf ]] && >| /etc/wpa_supplicant/wpa_supplicant.conf
	if [[ -f /etc/wpa_supplicant/wpa_supplicant.conf ]]; then
		cat > "/etc/wpa_supplicant/wpa_supplicant.conf" << EOF
ctrl_interface=/run/wpa_supplicant
ctrl_interface_group=wheel
update_config=1
fast_reauth=1

network={
   ssid=P"$_REDE_WIFI"
   psk="$_SENHA_WIFI"
   mesh_fwding=1
}
EOF
	fi
	return "$?"
}

sh_disableprintk() {
	if [ -w /proc/sys/kernel/printk ]; then
		echo 0 >/proc/sys/kernel/printk
	fi
}

sh_enableprintk() {
	if [ -w /proc/sys/kernel/printk ]; then
		echo 4 >/proc/sys/kernel/printk
	fi
}

sh_ascii_lines() {
	if [[ "$LANG" =~ 'UTF-8' ]]; then
		export NCURSES_NO_UTF8_ACS=0
	else
		export NCURSES_NO_UTF8_ACS=1
	fi
}

sh_checkroot() {
	if [ "$(id -u)" != "0" ]; then
		die "${red} erro: você não pode realizar esta operação a menos que seja root."
	fi
}

sh_checkDependencies() {
	local d
	local errorFound=0
	declare -a missing

	for d in "${DEPENDENCIES[@]}"; do
		[[ -z $(command -v "$d") ]] && missing+=("$d") && errorFound=1 && printf '%s\n' "${red}ERRO${reset}: não encontrei o comando ${cyan}'$d'${reset}"
	done
	if (( errorFound )); then
		echo "${yellow}--------------IMPOSSÍVEL CONTINUAR-------------${reset}"
		echo "Esse script precisa dos comandos listados acima" >&2
		echo "Instale-os e/ou verifique se estão no seu \$PATH" >&2
		echo "${yellow}-----------------------------------------------${reset}"

		if [[ "$distro" = 'void' ]] ; then
			echo
			if readconf "${yellow}Instalar o(s) comando(s) '${cyan}${missing[*]}${reset}'?"; then
				if xbps-install -S "${missing[*]}"; then
					die "INFO: Rode novamente o aplicativo"
				else
					die "ERRO na instalação dos comandos. Tente manualmente."
				fi
			fi
		fi
		die "ERRO: Instalação abortada..."
	fi
}

msg() {
	${DIALOG}               	\
		--no-collapse           \
		--title     "$1"        \
		--backtitle "$ccabec"	\
		--infobox   "\n$2"      \
		8 60
}

die() {
	if test $# -ge 2; then
		return 1
	fi
	local msg=$1; shift
	printf "%-75s\n" "${bold}${red}$msg${reset}" >&2
	sh_enableprintk
	exit 1
}

readconf() {
	read -r -p "$1 [S/n]"
	[[ ${REPLY^} == "" ]] && return 0
	[[ ${REPLY^} == N ]]  && return 1 || return 0
}

sh_cmd_job() {
	local cmsg="$1"
	local cjob="$2"
	local erro_fatal="$3"
	local lretval=0

	msg "INFO" "$cmsg"
	$cjob >>"$BOOTLOG" 2>&1
	return "$?"
}

sh_mkservices() {
	local aServices=('dhcpcd' 'wpa_supplicant')
	local service

	for service in "${aServices[@]}"
	do
		sh_cmd_job "Instalando pacote: $service" "xbps-install -Sy $service"
		sh_cmd_job "Ativando serviço : $service" "ln -sf /etc/sv/$service /etc/runit/runsvdir/current/"
		sh_cmd_job "Restartando serviço : $service" "sv restart $service"
	done
}

sh_confwifi() {
	while true
	do
		exec 3>&1
		wifitext=$(${DIALOG}						\
			--title		"** REDE WIFI **"		\
			--colors					      	   \
			--erase-on-exit						\
			--backtitle	"$ccabec"				\
			--insecure	"$@"						\
			--mixedform	"$LABEL"					\
			0 0 0										\
			"Rede Wifi : "	1 1 "$_REDE_WIFI"		1 15 40 0 0 \
			"Senha Wifi: " 2 1 "$_SENHA_WIFI"	2 15 40 0 1 \
			2>&1 1>&3)

			exit_status=$?
			case $exit_status in
				"$D_ESC"|"$D_CANCEL")
					clear
					return
					;;
				"$D_OK")
					mapfile -t <<< "$wifitext" aWifi
					_REDE_WIFI="${aWifi[0]}"
					_SENHA_WIFI="${aWifi[1]}"
					log_wait_msg 'Configurações efetuadas. Prosseguindo com instalação.'
					sh_update_wpa_suplicant
					sh_mkservices
					;;
			esac
		exec 3>&-
		return 0
	done
}

sh_checkroot
sh_checkDependencies
sh_disableprintk
sh_ascii_lines
sh_confwifi "$@"
sh_enableprintk
